###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Sorry to Bother You",
    "year": 2019,
    "language": "English"
}

###
GET http://localhost:3000/movies HTTP/1.1

###
GET http://localhost:3000/movies/61041b383628704ea0443c73 HTTP/1.1

###

PUT http://localhost:3000/movies/61041b383628704ea0453c73 HTTP/1.1
content-type: application/json

{
    "title": "Sorry to Bother You",
    "year": 2018,
    "language": "English"
}

###
DELETE http://localhost:3000/movies/61041b383628704ea0453c73 HTTP/1.1

