###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Umma",
    "year": 2022,
    "language": "English Korean"
}


###
GET http://localhost:3000/movies HTTP/1.1

###
GET http://localhost:3000/movies/62e02485a7d7c688947d7132

###
GET http://localhost:3000/movies/?year=2022

###
GET http://localhost:3000/movies/?language=English


###
PUT http://localhost:3000/movies/62e02a0a7b33b7e9885a5d41 HTTP/1.1
content-type: application/json

{
    "title": "Umma",
    "year": 2022,
    "language": "English"
}

###
DELETE http://localhost:3000/movies/62e02485a7d7c688947d7132 HTTP/1.1


###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Eternal Sunshine Of The Spotless Mind",
    "year": 2004,
    "language": "English"
}

###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "High Fidelity",
    "year": 2000,
    "language": "English"
}

###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Anchorman",
    "year": 2004,
    "language": "English"
}


###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "No Country For Old Men",
    "year": 2007,
    "language": "English"
}


###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "A Serious Man",
    "year": 2009,
    "language": "English"
}


###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "City Of God",
    "year": 2003,
    "language": "Portuguese"
}

###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Parasite",
    "year": 2019,
    "language": "Korean"
}
